FROM python:3.10

RUN pip install "lerobot[feetech]"
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt
ENV PYTHONPATH="/app"
WORKDIR /app
ENTRYPOINT ["/bin/bash"]
